POST http://localhost:5000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsdG8iLCJpZCI6IjYzZjFhZWRhMWJlMjAyNmFlMzY4Njk5YiIsImlhdCI6MTY3NjgwODQ2MH0.3TYMhGqvRiDAOXIL0ZJ8lUr-6sjWEVHeltOiVmhVZbM

{
    "title":"A Brief History of Time",
    "author":"Stephen Hawking",
    "url":"http://localhost:5000",
    "likes":"1800"
}

###

GET http://localhost:5000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsdG8iLCJpZCI6IjYzZjFhZWRhMWJlMjAyNmFlMzY4Njk5YiIsImlhdCI6MTY3NjgwODQ2MH0.3TYMhGqvRiDAOXIL0ZJ8lUr-6sjWEVHeltOiVmhVZbM


###
DELETE http://localhost:5000/api/blogs/63f219f25f6ed752bbf0117e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsdG8iLCJpZCI6IjYzZjFhZWRhMWJlMjAyNmFlMzY4Njk5YiIsImlhdCI6MTY3NjgwODQ2MH0.3TYMhGqvRiDAOXIL0ZJ8lUr-6sjWEVHeltOiVmhVZbM


###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username":"alto",
    "name":"Alto Haltman",
    "password":"altoCapHaltman"
}

###
GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "username":"alto",
    "password":"altoCapHaltman"
}
