POST http://localhost:5000/api/blogs
Content-Type: application/json

{
    "title":"A Brief History of Time",
    "author":"Stephen Hawking",
    "url":"http://localhost:5000",
    "likes":"1300"
}

###

GET http://localhost:5000/api/blogs

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username":"alto",
    "name":"Alto Haltman",
    "password":"altoCapHaltman"
}

###
GET http://localhost:5000/api/users
